# api version
version: '2'

services: 
  jianyu: 
    build: ./Jianyu
    container_name: jianyu
    environment: 
        - VIRTUAL_HOST=jianyu.familyoffeng.us,familyoffeng.us
    image: jianyu
    network_mode: "bridge"
    volumes: 
        - ./Jianyu:/usr/share/nginx/html
  api: 
    build: ./api
    container_name: api
    environment: 
        - VIRTUAL_HOST=api.familyoffeng.us
    image: api
    network_mode: "bridge"
    volumes:
        - ./api:/usr/share/nginx/html
