# api version
version: '2'

services:
  jianyu:
    build: ./JavaScriptPractice
    container_name: jianyu
    environment:
        - VIRTUAL_HOST=jianyu.familyoffeng.us,familyoffeng.us
    image: jianyu
    network_mode: "bridge"
    volumes:
        - ./Jianyu:/usr/share/nginx/html
