# api version
version: '2'

services: 
  jianyu: 
    build: ./Jianyu
    environment: 
        - VIRTUAL_HOST=jianyu.familyoffeng.us
    network_mode: "bridge"
    volumes: 
        - Jianyu:/usr/share/nginx/html

volumes:
  Jianyu
